### ISSUE TITLE
Custom errors

### ISSUE THREAD

**Issue by adam-26** [mwitkow/go-grpc-middleware#17]
Hi,

When using the logging middleware, its difficult to use custom errors in handlers/other interceptors because the logging middleware expects an `rpcError`type to determine the grpc error code.

By adding another func (that extracts a grpc error code from an error) to the logging options, it would be easy to enable the use of custom errors types. This can be done without changing the current default behavior.

I'll submit a PR.

**Comment by mwitkow** [comment]
Merged :) Thanks
